/*
===============================================================================
CAD-to-ERP Analytics Queries
===============================================================================

Purpose:
    This file contains example SQL queries used to analyze engineering,
    supplier, inventory, and Bill of Materials (BOM) data generated by the
    CAD-to-ERP pipeline.

Business Use Cases:
    - Inventory monitoring and replenishment planning
    - Supplier dependency and risk analysis
    - Engineering change and review tracking
    - Assembly complexity analysis
    - Manufacturing operational reporting

Data Sources:
    - parts
    - suppliers
    - inventory
    - bom

Notes:
    These queries are intended to demonstrate how transformed engineering
    and operational datasets can support downstream reporting and
    decision-making workflows commonly found in manufacturing ERP systems.

===============================================================================
*/
-- Supplier inventory exposure
SELECT
    p.supplier_id,
    s.supplier_name,
    COUNT(p.part_number) AS supported_parts,
    SUM(i.stock_quantity) AS total_stock_on_hand
FROM parts p
JOIN suppliers s
    ON p.supplier_id = s.supplier_id
JOIN inventory i
    ON p.part_number = i.part_number
GROUP BY p.supplier_id, s.supplier_name
ORDER BY total_stock_on_hand DESC;


-- Parts used across multiple assemblies
SELECT
    part_number,
    COUNT(DISTINCT assembly_id) AS assembly_usage_count
FROM bom
GROUP BY part_number
HAVING COUNT(DISTINCT assembly_id) > 1
ORDER BY assembly_usage_count DESC;


-- Inventory risk by assembly
SELECT
    b.assembly_id,
    b.assembly_name,
    COUNT(*) AS total_components,
    SUM(
        CASE
            WHEN i.below_reorder_level = TRUE THEN 1
            ELSE 0
        END
    ) AS components_below_reorder
FROM bom b
JOIN inventory i
    ON b.part_number = i.part_number
GROUP BY b.assembly_id, b.assembly_name
ORDER BY components_below_reorder DESC;
